In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd

In [ ]:
titanic=pd.read_csv(r"/content/titanic.csv")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
print(titanic)
print(titanic.head())
print(titanic.tail())
print(titanic.info())
print(titanic.dtypes)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
for i in titanic.columns:
    print(i,'\t',':','\n',titanic[i].unique())

PassengerId 	 :
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270
 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342
 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378
 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396
 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414
 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450
 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468
 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504
 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522
 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540
 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558
 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576
 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594
 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612
 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630
 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648
 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666
 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684
 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701 702
 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720
 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738
 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755 756
 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774
 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791 792
 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809 810
 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827 828
 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845 846
 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863 864
 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881 882
 883 884 885 886 887 888 889 890 891]
Survived 	 :
 [0 1]
Pclass 	 :
 [3 1 2]
Name 	 :
 ['Braund, Mr. Owen Harris'
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'
 'Heikkinen, Miss. Laina' 'Futrelle, Mrs. Jacques Heath (Lily May Peel)'
 'Allen, Mr. William Henry' 'Moran, Mr. James' 'McCarthy, Mr. Timothy J'
 'Palsson, Master. Gosta Leonard'
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)'
 'Nasser, Mrs. Nicholas (Adele Achem)' 'Sandstrom, Miss. Marguerite Rut'
 'Bonnell, Miss. Elizabeth' 'Saundercock, Mr. William Henry'
 'Andersson, Mr. Anders Johan' 'Vestrom, Miss. Hulda Amanda Adolfina'
 'Hewlett, Mrs. (Mary D Kingcome) ' 'Rice, Master. Eugene'
 'Williams, Mr. Charles Eugene'
 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)'
 'Masselmani, Mrs. Fatima' 'Fynney, Mr. Joseph J' 'Beesley, Mr. Lawrence'
 'McGowan, Miss. Anna "Annie"' 'Sloper, Mr. William Thompson'
 'Palsson, Miss. Torborg Danira'
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)'
 'Emir, Mr. Farred Chehab' 'Fortune, Mr. Charles Alexander'
 'O\'Dwyer, Miss. Ellen "Nellie"' 'Todoroff, Mr. Lalio'
 'Uruchurtu, Don. Manuel E'
 'Spencer, Mrs. William Augustus (Marie Eugenie)'
 'Glynn, Miss. Mary Agatha' 'Wheadon, Mr. Edward H'
 'Meyer, Mr. Edgar Joseph' 'Holverson, Mr. Alexander Oskar'
 'Mamee, Mr. Hanna' 'Cann, Mr. Ernest Charles'
 'Vander Planke, Miss. Augusta Maria' 'Nicola-Yarred, Miss. Jamila'
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)'
 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)'
 'Kraeff, Mr. Theodor' 'Laroche, Miss. Simonne Marie Anne Andree'
 'Devaney, Miss. Margaret Delia' 'Rogers, Mr. William John'
 'Lennon, Mr. Denis' "O'Driscoll, Miss. Bridget" 'Samaan, Mr. Youssef'
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)'
 'Panula, Master. Juha Niilo' 'Nosworthy, Mr. Richard Cater'
 'Harper, Mrs. Henry Sleeper (Myna Haxtun)'
 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)'
 'Ostby, Mr. Engelhart Cornelius' 'Woolner, Mr. Hugh' 'Rugg, Miss. Emily'
 'Novel, Mr. Mansouer' 'West, Miss. Constance Mirium'
 'Goodwin, Master. William Frederick' 'Sirayanian, Mr. Orsen'
 'Icard, Miss. Amelie' 'Harris, Mr. Henry Birkhardt'
 'Skoog, Master. Harald' 'Stewart, Mr. Albert A'
 'Moubarek, Master. Gerios' 'Nye, Mrs. (Elizabeth Ramell)'
 'Crease, Mr. Ernest James' 'Andersson, Miss. Erna Alexandra'
 'Kink, Mr. Vincenz' 'Jenkin, Mr. Stephen Curnow'
 'Goodwin, Miss. Lillian Amy' 'Hood, Mr. Ambrose Jr'
 'Chronopoulos, Mr. Apostolos' 'Bing, Mr. Lee' 'Moen, Mr. Sigurd Hansen'
 'Staneff, Mr. Ivan' 'Moutal, Mr. Rahamin Haim'
 'Caldwell, Master. Alden Gates' 'Dowdell, Miss. Elizabeth'
 'Waelens, Mr. Achille' 'Sheerlinck, Mr. Jan Baptist'
 'McDermott, Miss. Brigdet Delia' 'Carrau, Mr. Francisco M'
 'Ilett, Miss. Bertha'
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)'
 'Ford, Mr. William Neal' 'Slocovski, Mr. Selman Francis'
 'Fortune, Miss. Mabel Helen' 'Celotti, Mr. Francesco'
 'Christmann, Mr. Emil' 'Andreasson, Mr. Paul Edvin'
 'Chaffee, Mr. Herbert Fuller' 'Dean, Mr. Bertram Frank'
 'Coxon, Mr. Daniel' 'Shorney, Mr. Charles Joseph'
 'Goldschmidt, Mr. George B' 'Greenfield, Mr. William Bertram'
 'Doling, Mrs. John T (Ada Julia Bone)' 'Kantor, Mr. Sinai'
 'Petranec, Miss. Matilda' 'Petroff, Mr. Pastcho ("Pentcho")'
 'White, Mr. Richard Frasar' 'Johansson, Mr. Gustaf Joel'
 'Gustafsson, Mr. Anders Vilhelm' 'Mionoff, Mr. Stoytcho'
 'Salkjelsvik, Miss. Anna Kristine' 'Moss, Mr. Albert Johan'
 'Rekic, Mr. Tido' 'Moran, Miss. Bertha' 'Porter, Mr. Walter Chamberlain'
 'Zabour, Miss. Hileni' 'Barton, Mr. David John' 'Jussila, Miss. Katriina'
 'Attalah, Miss. Malake' 'Pekoniemi, Mr. Edvard' 'Connors, Mr. Patrick'
 'Turpin, Mr. William John Robert' 'Baxter, Mr. Quigg Edmond'
 'Andersson, Miss. Ellis Anna Maria' 'Hickman, Mr. Stanley George'
 'Moore, Mr. Leonard Charles' 'Nasser, Mr. Nicholas' 'Webber, Miss. Susan'
 'White, Mr. Percival Wayland' 'Nicola-Yarred, Master. Elias'
 'McMahon, Mr. Martin' 'Madsen, Mr. Fridtjof Arne' 'Peter, Miss. Anna'
 'Ekstrom, Mr. Johan' 'Drazenoic, Mr. Jozef'
 'Coelho, Mr. Domingos Fernandeo'
 'Robins, Mrs. Alexander A (Grace Charity Laury)'
 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)'
 'Sobey, Mr. Samuel James Hayden' 'Richard, Mr. Emile'
 'Newsom, Miss. Helen Monypeny' 'Futrelle, Mr. Jacques Heath'
 'Osen, Mr. Olaf Elon' 'Giglio, Mr. Victor'
 'Boulos, Mrs. Joseph (Sultana)' 'Nysten, Miss. Anna Sofia'
 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)'
 'Burke, Mr. Jeremiah' 'Andrew, Mr. Edgardo Samuel'
 'Nicholls, Mr. Joseph Charles'
 'Andersson, Mr. August Edvard ("Wennerstrom")'
 'Ford, Miss. Robina Maggie "Ruby"'
 'Navratil, Mr. Michel ("Louis M Hoffman")'
 'Byles, Rev. Thomas Roussel Davids' 'Bateman, Rev. Robert James'
 'Pears, Mrs. Thomas (Edith Wearne)' 'Meo, Mr. Alfonzo'
 'van Billiard, Mr. Austin Blyler' 'Olsen, Mr. Ole Martin'
 'Williams, Mr. Charles Duane' 'Gilnagh, Miss. Katherine "Katie"'
 'Corn, Mr. Harry' 'Smiljanic, Mr. Mile' 'Sage, Master. Thomas Henry'
 'Cribb, Mr. John Hatfield'
 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)'
 'Bengtsson, Mr. John Viktor' 'Calic, Mr. Jovo'
 'Panula, Master. Eino Viljami'
 'Goldsmith, Master. Frank John William "Frankie"'
 'Chibnall, Mrs. (Edith Martha Bowerman)'
 'Skoog, Mrs. William (Anna Bernhardina Karlsson)' 'Baumann, Mr. John D'
 'Ling, Mr. Lee' 'Van der hoef, Mr. Wyckoff' 'Rice, Master. Arthur'
 'Johnson, Miss. Eleanor Ileen' 'Sivola, Mr. Antti Wilhelm'
 'Smith, Mr. James Clinch' 'Klasen, Mr. Klas Albin'
 'Lefebre, Master. Henry Forbes' 'Isham, Miss. Ann Elizabeth'
 'Hale, Mr. Reginald' 'Leonard, Mr. Lionel' 'Sage, Miss. Constance Gladys'
 'Pernot, Mr. Rene' 'Asplund, Master. Clarence Gustaf Hugo'
 'Becker, Master. Richard F' 'Kink-Heilmann, Miss. Luise Gretchen'
 'Rood, Mr. Hugh Roscoe'
 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)'
 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")' 'Bourke, Mr. John'
 'Turcin, Mr. Stjepan' 'Pinsky, Mrs. (Rosa)' 'Carbines, Mr. William'
 'Andersen-Jensen, Miss. Carla Christine Nielsine'
 'Navratil, Master. Michel M' 'Brown, Mrs. James Joseph (Margaret Tobin)'
 'Lurette, Miss. Elise' 'Mernagh, Mr. Robert'
 'Olsen, Mr. Karl Siegwart Andreas' 'Madigan, Miss. Margaret "Maggie"'
 'Yrois, Miss. Henriette ("Mrs Harbeck")' 'Vande Walle, Mr. Nestor Cyriel'
 'Sage, Mr. Frederick' 'Johanson, Mr. Jakob Alfred' 'Youseff, Mr. Gerious'
 'Cohen, Mr. Gurshon "Gus"' 'Strom, Miss. Telma Matilda'
 'Backstrom, Mr. Karl Alfred' 'Albimona, Mr. Nassef Cassem'
 'Carr, Miss. Helen "Ellen"' 'Blank, Mr. Henry' 'Ali, Mr. Ahmed'
 'Cameron, Miss. Clear Annie' 'Perkin, Mr. John Henry'
 'Givard, Mr. Hans Kristensen' 'Kiernan, Mr. Philip'
 'Newell, Miss. Madeleine' 'Honkanen, Miss. Eliina'
 'Jacobsohn, Mr. Sidney Samuel' 'Bazzani, Miss. Albina'
 'Harris, Mr. Walter' 'Sunderland, Mr. Victor Francis'
 'Bracken, Mr. James H' 'Green, Mr. George Henry' 'Nenkoff, Mr. Christo'
 'Hoyt, Mr. Frederick Maxfield' 'Berglund, Mr. Karl Ivar Sven'
 'Mellors, Mr. William John' 'Lovell, Mr. John Hall ("Henry")'
 'Fahlstrom, Mr. Arne Jonas' 'Lefebre, Miss. Mathilde'
 'Harris, Mrs. Henry Birkhardt (Irene Wallach)' 'Larsson, Mr. Bengt Edvin'
 'Sjostedt, Mr. Ernst Adolf' 'Asplund, Miss. Lillian Gertrud'
 'Leyson, Mr. Robert William Norman' 'Harknett, Miss. Alice Phoebe'
 'Hold, Mr. Stephen' 'Collyer, Miss. Marjorie "Lottie"'
 'Pengelly, Mr. Frederick William' 'Hunt, Mr. George Henry'
 'Zabour, Miss. Thamine' 'Murphy, Miss. Katherine "Kate"'
 'Coleridge, Mr. Reginald Charles' 'Maenpaa, Mr. Matti Alexanteri'
 'Attalah, Mr. Sleiman' 'Minahan, Dr. William Edward'
 'Lindahl, Miss. Agda Thorilda Viktoria' 'Hamalainen, Mrs. William (Anna)'
 'Beckwith, Mr. Richard Leonard' 'Carter, Rev. Ernest Courtenay'
 'Reed, Mr. James George' 'Strom, Mrs. Wilhelm (Elna Matilda Persson)'
 'Stead, Mr. William Thomas' 'Lobb, Mr. William Arthur'
 'Rosblom, Mrs. Viktor (Helena Wilhelmina)'
 'Touma, Mrs. Darwis (Hanne Youssef Razi)'
 'Thorne, Mrs. Gertrude Maybelle' 'Cherry, Miss. Gladys'
 'Ward, Miss. Anna' 'Parrish, Mrs. (Lutie Davis)' 'Smith, Mr. Thomas'
 'Asplund, Master. Edvin Rojj Felix' 'Taussig, Mr. Emil'
 'Harrison, Mr. William' 'Henry, Miss. Delia' 'Reeves, Mr. David'
 'Panula, Mr. Ernesti Arvid' 'Persson, Mr. Ernst Ulrik'
 'Graham, Mrs. William Thompson (Edith Junkins)' 'Bissette, Miss. Amelia'
 'Cairns, Mr. Alexander' 'Tornquist, Mr. William Henry'
 'Mellinger, Mrs. (Elizabeth Anne Maidment)' 'Natsch, Mr. Charles H'
 'Healy, Miss. Hanora "Nora"' 'Andrews, Miss. Kornelia Theodosia'
 'Lindblom, Miss. Augusta Charlotta' 'Parkes, Mr. Francis "Frank"'
 'Rice, Master. Eric' 'Abbott, Mrs. Stanton (Rosa Hunt)'
 'Duane, Mr. Frank' 'Olsson, Mr. Nils Johan Goransson'
 'de Pelsmaeker, Mr. Alfons' 'Dorking, Mr. Edward Arthur'
 'Smith, Mr. Richard William' 'Stankovic, Mr. Ivan'
 'de Mulder, Mr. Theodore' 'Naidenoff, Mr. Penko' 'Hosono, Mr. Masabumi'
 'Connolly, Miss. Kate' 'Barber, Miss. Ellen "Nellie"'
 'Bishop, Mrs. Dickinson H (Helen Walton)' 'Levy, Mr. Rene Jacques'
 'Haas, Miss. Aloisia' 'Mineff, Mr. Ivan' 'Lewy, Mr. Ervin G'
 'Hanna, Mr. Mansour' 'Allison, Miss. Helen Loraine'
 'Saalfeld, Mr. Adolphe' 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)'
 'Kelly, Miss. Anna Katherine "Annie Kate"' 'McCoy, Mr. Bernard'
 'Johnson, Mr. William Cahoone Jr' 'Keane, Miss. Nora A'
 'Williams, Mr. Howard Hugh "Harry"' 'Allison, Master. Hudson Trevor'
 'Fleming, Miss. Margaret'
 'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)'
 'Abelson, Mr. Samuel' 'Francatelli, Miss. Laura Mabel'
 'Hays, Miss. Margaret Bechstein' 'Ryerson, Miss. Emily Borie'
 'Lahtinen, Mrs. William (Anna Sylfven)' 'Hendekovic, Mr. Ignjac'
 'Hart, Mr. Benjamin' 'Nilsson, Miss. Helmina Josefina'
 'Kantor, Mrs. Sinai (Miriam Sternin)' 'Moraweck, Dr. Ernest'
 'Wick, Miss. Mary Natalie'
 'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)'
 'Dennis, Mr. Samuel' 'Danoff, Mr. Yoto' 'Slayter, Miss. Hilda Mary'
 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)'
 'Sage, Mr. George John Jr' 'Young, Miss. Marie Grice'
 'Nysveen, Mr. Johan Hansen' 'Ball, Mrs. (Ada E Hall)'
 'Goldsmith, Mrs. Frank John (Emily Alice Brown)'
 'Hippach, Miss. Jean Gertrude' 'McCoy, Miss. Agnes' 'Partner, Mr. Austen'
 'Graham, Mr. George Edward' 'Vander Planke, Mr. Leo Edmondus'
 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)' 'Denkoff, Mr. Mitto'
 'Pears, Mr. Thomas Clinton' 'Burns, Miss. Elizabeth Margaret'
 'Dahl, Mr. Karl Edwart' 'Blackwell, Mr. Stephen Weart'
 'Navratil, Master. Edmond Roger' 'Fortune, Miss. Alice Elizabeth'
 'Collander, Mr. Erik Gustaf' 'Sedgwick, Mr. Charles Frederick Waddington'
 'Fox, Mr. Stanley Hubert' 'Brown, Miss. Amelia "Mildred"'
 'Smith, Miss. Marion Elsie' 'Davison, Mrs. Thomas Henry (Mary E Finck)'
 'Coutts, Master. William Loch "William"' 'Dimic, Mr. Jovan'
 'Odahl, Mr. Nils Martin' 'Williams-Lambert, Mr. Fletcher Fellows'
 'Elias, Mr. Tannous' 'Arnold-Franchi, Mr. Josef' 'Yousif, Mr. Wazli'
 'Vanden Steen, Mr. Leo Peter' 'Bowerman, Miss. Elsie Edith'
 'Funk, Miss. Annie Clemmer' 'McGovern, Miss. Mary'
 'Mockler, Miss. Helen Mary "Ellie"' 'Skoog, Mr. Wilhelm'
 'del Carlo, Mr. Sebastiano' 'Barbara, Mrs. (Catherine David)'
 'Asim, Mr. Adola' "O'Brien, Mr. Thomas" 'Adahl, Mr. Mauritz Nils Martin'
 'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)'
 'Moussa, Mrs. (Mantoura Boulos)' 'Jermyn, Miss. Annie'
 'Aubart, Mme. Leontine Pauline' 'Harder, Mr. George Achilles'
 'Wiklund, Mr. Jakob Alfred' 'Beavan, Mr. William Thomas'
 'Ringhini, Mr. Sante' 'Palsson, Miss. Stina Viola'
 'Meyer, Mrs. Edgar Joseph (Leila Saks)' 'Landergren, Miss. Aurora Adelia'
 'Widener, Mr. Harry Elkins' 'Betros, Mr. Tannous'
 'Gustafsson, Mr. Karl Gideon' 'Bidois, Miss. Rosalie'
 'Nakid, Miss. Maria ("Mary")' 'Tikkanen, Mr. Juho'
 'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)'
 'Plotcharsky, Mr. Vasil' 'Davies, Mr. Charles Henry'
 'Goodwin, Master. Sidney Leonard' 'Buss, Miss. Kate'
 'Sadlier, Mr. Matthew' 'Lehmann, Miss. Bertha'
 'Carter, Mr. William Ernest' 'Jansson, Mr. Carl Olof'
 'Gustafsson, Mr. Johan Birger' 'Newell, Miss. Marjorie'
 'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)'
 'Johansson, Mr. Erik' 'Olsson, Miss. Elina' 'McKane, Mr. Peter David'
 'Pain, Dr. Alfred' 'Trout, Mrs. William H (Jessie L)'
 'Niskanen, Mr. Juha' 'Adams, Mr. John' 'Jussila, Miss. Mari Aina'
 'Hakkarainen, Mr. Pekka Pietari' 'Oreskovic, Miss. Marija'
 'Gale, Mr. Shadrach' 'Widegren, Mr. Carl/Charles Peter'
 'Richards, Master. William Rowe' 'Birkeland, Mr. Hans Martin Monsen'
 'Lefebre, Miss. Ida' 'Sdycoff, Mr. Todor' 'Hart, Mr. Henry'
 'Minahan, Miss. Daisy E' 'Cunningham, Mr. Alfred Fleming'
 'Sundman, Mr. Johan Julian' 'Meek, Mrs. Thomas (Annie Louise Rowley)'
 'Drew, Mrs. James Vivian (Lulu Thorne Christian)'
 'Silven, Miss. Lyyli Karoliina' 'Matthews, Mr. William John'
 'Van Impe, Miss. Catharina' 'Gheorgheff, Mr. Stanio'
 'Charters, Mr. David' 'Zimmerman, Mr. Leo'
 'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)'
 'Rosblom, Mr. Viktor Richard' 'Wiseman, Mr. Phillippe'
 'Clarke, Mrs. Charles V (Ada Maria Winfield)'
 'Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")'
 'Flynn, Mr. James' 'Pickard, Mr. Berk (Berk Trembisky)'
 'Bjornstrom-Steffansson, Mr. Mauritz Hakan'
 'Thorneycroft, Mrs. Percival (Florence Kate White)'
 'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)'
 'Kallio, Mr. Nikolai Erland' 'Silvey, Mr. William Baird'
 'Carter, Miss. Lucile Polk' 'Ford, Miss. Doolina Margaret "Daisy"'
 'Richards, Mrs. Sidney (Emily Hocking)' 'Fortune, Mr. Mark'
 'Kvillner, Mr. Johan Henrik Johannesson'
 'Hart, Mrs. Benjamin (Esther Ada Bloomfield)' 'Hampe, Mr. Leon'
 'Petterson, Mr. Johan Emil' 'Reynaldo, Ms. Encarnacion'
 'Johannesen-Bratthammer, Mr. Bernt' 'Dodge, Master. Washington'
 'Mellinger, Miss. Madeleine Violet' 'Seward, Mr. Frederic Kimber'
 'Baclini, Miss. Marie Catherine' 'Peuchen, Major. Arthur Godfrey'
 'West, Mr. Edwy Arthur' 'Hagland, Mr. Ingvald Olai Olsen'
 'Foreman, Mr. Benjamin Laventall' 'Goldenberg, Mr. Samuel L'
 'Peduzzi, Mr. Joseph' 'Jalsevac, Mr. Ivan' 'Millet, Mr. Francis Davis'
 'Kenyon, Mrs. Frederick R (Marion)' 'Toomey, Miss. Ellen'
 "O'Connor, Mr. Maurice" 'Anderson, Mr. Harry' 'Morley, Mr. William'
 'Gee, Mr. Arthur H' 'Milling, Mr. Jacob Christian' 'Maisner, Mr. Simon'
 'Goncalves, Mr. Manuel Estanslas' 'Campbell, Mr. William'
 'Smart, Mr. John Montgomery' 'Scanlan, Mr. James'
 'Baclini, Miss. Helene Barbara' 'Keefe, Mr. Arthur' 'Cacic, Mr. Luka'
 'West, Mrs. Edwy Arthur (Ada Mary Worth)'
 'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)'
 'Strandberg, Miss. Ida Sofia' 'Clifford, Mr. George Quincy'
 'Renouf, Mr. Peter Henry' 'Braund, Mr. Lewis Richard'
 'Karlsson, Mr. Nils August' 'Hirvonen, Miss. Hildur E'
 'Goodwin, Master. Harold Victor' 'Frost, Mr. Anthony Wood "Archie"'
 'Rouse, Mr. Richard Henry' 'Turkula, Mrs. (Hedwig)'
 'Bishop, Mr. Dickinson H' 'Lefebre, Miss. Jeannie'
 'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)'
 'Kent, Mr. Edward Austin' 'Somerton, Mr. Francis William'
 'Coutts, Master. Eden Leslie "Neville"'
 'Hagland, Mr. Konrad Mathias Reiersen' 'Windelov, Mr. Einar'
 'Molson, Mr. Harry Markland' 'Artagaveytia, Mr. Ramon'
 'Stanley, Mr. Edward Roland' 'Yousseff, Mr. Gerious'
 'Eustis, Miss. Elizabeth Mussey' 'Shellard, Mr. Frederick William'
 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)' 'Svensson, Mr. Olof'
 'Calic, Mr. Petar' 'Canavan, Miss. Mary' "O'Sullivan, Miss. Bridget Mary"
 'Laitinen, Miss. Kristina Sofia' 'Maioni, Miss. Roberta'
 'Penasco y Castellana, Mr. Victor de Satode'
 'Quick, Mrs. Frederick Charles (Jane Richards)'
 'Bradley, Mr. George ("George Arthur Brayton")'
 'Olsen, Mr. Henry Margido' 'Lang, Mr. Fang' 'Daly, Mr. Eugene Patrick'
 'Webber, Mr. James' 'McGough, Mr. James Robert'
 'Rothschild, Mrs. Martin (Elizabeth L. Barrett)' 'Coleff, Mr. Satio'
 'Walker, Mr. William Anderson' 'Lemore, Mrs. (Amelia Milley)'
 'Ryan, Mr. Patrick'
 'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)'
 'Pavlovic, Mr. Stefo' 'Perreault, Miss. Anne' 'Vovk, Mr. Janko'
 'Lahoud, Mr. Sarkis' 'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)'
 'Kassem, Mr. Fared' 'Farrell, Mr. James' 'Ridsdale, Miss. Lucy'
 'Farthing, Mr. John' 'Salonen, Mr. Johan Werner'
 'Hocking, Mr. Richard George' 'Quick, Miss. Phyllis May'
 'Toufik, Mr. Nakli' 'Elias, Mr. Joseph Jr'

In [ ]:
print(titanic.describe(include="O"))
titanic.Embarked.fillna('S',inplace=True)

        Age
count   891
unique   89
top       S
freq    177

In [ ]:
print(titanic.describe(include="O"))
titanic.Age.fillna('20',inplace=True)

        Age
count   891
unique   89
top       S
freq    177

In [ ]:
print(titanic.describe(include="N"))
titanic.Cabin.fillna('20',inplace=True)

TypeError: data type 'N' not understood

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
titanic['Name']=le.fit_transform(titanic['Name'])
print(titanic['Name'].unique())

[108 190 353 272  15 554 515 624 412 576 727  95 729  28 840 359 682 867
 839 512 273  80 523 765 626  44 240 260 605 813 828 776 289 856 535 372
 505 134 837 589   7 827 446 456 212 697 473 604 726  38 629 594 333 246
 620 873 707 595 853 299 749 385 337 755 784 560 596 185  25 440 396 300
 376 161  87 546 778 563 127 223 842 737 519 141 386  52 255 764 259 149
 159  31 150 209 184 740 292 308 219 422 656 658 858 405 312 542 724 559
 675 552 667 882  67 417  46 645 178 826  70  24 362 551 575 848 857 588
 525 499 653 234 225 165 695 851 772 685 585 271 618 282  99 597 319 116
  32 586  29 254 580 121  68 643 532 889 612 866 287 181 767 716 186 847
  82 129 628 293 157 760  69 486 832 680 408 752 769 444 464 388 320 474
 717 650  41  76 441 700 601 698 101 823 664 136  20 579 113 495 533 611
 497 881 834 721 403 878 166 789  51   9 140  94  12 131 649 288 437 582
 375 390  72 338 791 105 306 581 379  83 531 492 243 467 339 460 754  43
 479 329 370 172 648 383 883 567 169 500  47 539 481 322  78 147 673 790
 782 487 702 819 808 156 844 636 771  42 799 340 356 674 631 652 305  91
 125 817 530 577 350  33 482 634 681   2 227 614 887 221 770 779 886 570
 378 177  65  90 477 315 541 478 324  17 714  71 431 518 411 428 868  16
 248 647   3 263 348 710 449 355 342 590 423 555 859 775 211 200 762 128
 722 877 598  60 295 363 517 637 304 838 265 210 642 117 192  93 578 258
 170 733 262 111 768 207 183 215 608 870 237  37 879 835 104 270 522 545
 759 888  64  40 599   5 845 562 400  48 328 863  75 690 625 536 454 862
  85 314  86 572 811 373 665 205 298 118 715 468 144 393 313 583 728 404
 613 524 623 821 592   6 418 318 616 274 861 687  88 465 732 343 540 191
 792 528 226 742 513 829 281 155 884 198 701 872 162 662 249 663  92 810
 491 420 744 143 253 688 261 447 344 323 659 679 402 216 529 735  55 661
 854 316 257 290 644 392 537 436 815 603  21 557 280 538 502 296 132 766
 731  54 430 124 855 401 787 164 676 107 425 365 297 268 706 825  89 466
 381 435 774 182 317 871 547  39 781 880 242 738  18 796 130 133 607 450
 501 646 670 106 610 455 195 849 521 705 168 843 472 709  35 641 651 841
 448 364 427 244 689 245 725 366 669 818 236 654 123 341 120 461 692 266
 188  26  27  73 222 587  74 622 294 203 804 736 600 463 609 874 228 693
 800 885 558 751 593 746 527 204 786 627 217 416 336  36 251 432 708 639
 277 745 135 419 160 805 224 703 640 798 395 267 284 566 691 783 238 100
 154 830 470 409  98 229 391 761 335 816 374 483 424 199 458 741  30 394
 568 377 110 357 197 488  77 279 875 439 573 327 103 794 442 490  96 602
  66 494 777 635 757 206 469 173 633 809 397 723 758 252  53 332 180 747
 865 780 544 218 421 606 352 360 671 102 232 584 264  57 171 167 484 361
 119 699 179 802 114 202 543 864 846 231 730 824 302 137 655 345 615 301
 112 457 632 194 247 498 213 426 452 713 850 153 433 565 803 382  45 743
  63 275 326 556 434 126 163 561 514 443 801 459 307 773 241 822 520 410
 331 399 286 368 151 617 677 507 115 387  14 346 445  84 820 869 256 476
 389 574 347 148 711 526 788 187   1 748 511 176 852 549 833 415 358 321
 138  58 806 704 276 591  62 146 233 369 109 506 553 309 480 398 496 235
 367 569 812 239 438 694  50 214 489 414  13 330 753 683 208 310 429 278
 719 380 201 621 462 619 384 831 666 174 142 807 351 406  34 660 534 152
  10 475 763  23 814 269 354 504 371 756 349 493 678 550 630 250 453 503
 516 785 876 686 712  49  19 175 638 750 158 508  11 564 734 471 189   0
 720 509 334 291  22 795  97 485 145   8 860 196  56 672 325 283 797 718
 285 122 230 696 890 407  59  79 139 836   4 571 311 657 451 668 739 510
 193  61 793 684 548 303 413  81 220]

In [ ]:
titanic['Sex']=le.fit_transform(titanic['Sex'])
print(titanic['Sex'].unique())

[1 0]

In [ ]:
titanic['Cabin']=le.fit_transform(titanic['Cabin'])
print(titanic['Cabin'].unique())

[ 15  82  56 130 146  50 112  13  64  42 102  24  72  22  81 143 141 123
  12  92  99  53  37 117 139 108  46 142  62 124  19  14  70 145   9  29
  44   8 104  94  88  79 103  84  41 135  47  58  90  55 114   3  32  91
  63  52  75 126  73  36  77 125  66  18  57  86 128 147  60 105  25 132
  80  48 116 129  10  51  54  87 127  98 118 134   1  26  65  97  43 122
 107  40  89  27  28  21  83  78   2  49  76   0 136  30   4  96 111 115
   5  34   7 109 133  59  39  35 110  33  20 140  74 121  85  67 138  16
 106  68 101 119  93 137 144  23 113  45  95  11  17  38 131  69 100 120
   6  71  31  61]

In [ ]:
titanic['Ticket']=le.fit_transform(titanic['Ticket'])
print(titanic['Ticket'].unique())

[523 596 669  49 472 275  85 395 344 132 616  38 535 333 413 153 480 151
 301 184 139 152 278  42 329 179  95 283 362 598 586 288 549 600  43 202
 514 302 186 507  53 391 634 282 617 462  76 190 377 249 522 587 239  29
  94 555 215 561 566 197  32 457 337 601 189 553 623 248 270 557 621 204
  80 347 355 473 158 432 304 311 280  25 637 247 676 652 297 298 341 678
 548 428 475 607 612 117 150 384 361 417 505 245 354 296 254 388 469   2
 193 274 491 176 666 460 585 540 219 463 541 196 318 380 640 537 111 552
 630  55 504 592 203 332 668 438 118 558 405 113 147 622  36 516 538 573
 595 418 654 258 568 470 559 323 265 423  28 576   5 659  90 412 488 593
 169 574 629 114 271  34 459  11 435 386 122 227 406 604 452 494 461 160
 306 242 177 530 316 216 445  17 642 570 526 163 443 416 670 142  63 679
 653 105 102 375  93 615 672 525 125 322 128 554 677 198 556 231 636 444
 674 658 213  92 325 166  54 144 422  31 536 458 185 589   0 608 115 482
   1  16 478 546 334 588 613  47 162 594 465  71 326 135 551 290 340 310
 533  24 378 308 353 134 464  91  64 635 376 374 606 212  37  98 513 441
 109 527  83 611 575 584  59 602 167 382 571 343 232 453  81 524 365 124
 299 229   7  20 605 370 510  39 159 149 112 157 257 483 562 262 503  30
 214 182 314 131 279 285 633 211 641 544   4 175  78 581  58 244 273 545
  27 183 324 610 187 665 371 220 447 625  33 401 246 410 414 226 146 140
 663 292 492 267 230 321 237 255 367 487 655 295 224 168 225 307 392 534
 259 331 521 100 170 437 644   3 476 627 657  72 547 305 328 116 499 289
  45 194  40 497  22  84 528 379  73  86 572 468  96 429   6 121 539 639
  44 421 272 263 628 509 252 315 411 251 136 531 489  61 517 498 649  41
 603 518 454 564 402 261 433 276 490 180  10 542 479 648 577 599 356 456
 560 110 381  67 390 173 217 446 673 583 250 235 181 210 260  21 614 426
  75 680 233 501 631 148 284 171 335  52  57 300 471 389 103 651 645 519
 352 207 415 624  60 578  77 520 420 143 209 661 133  68 291 129  74  79
 515 656 532 434 626 155 192 360  46 430   9 396 385  50 638 467 431 106
 253 188  56 400 495 455 104 369 286 218 345  70  13 130 664 409 373  69
 620 567 366 512 277 439 368 241 172 496 357 660 123 256 529  99 240 569
 550 145 138 397 294 493 281 500 372 403 141  89 393 200  48 156 425 419
 346 579 449 398 108 580 582  19 506 164 348 293 440 319 408  65 161  51
 266 451 127 667 137 228 119 349 364  82 477 662 165  35 287 234 486 312
 351 404 238 424 646 191 327  18 436 511 313 407 619 201 236 330 481 450
 208  26 675 643 474 243  66 597 350 223  87 383 206 174 338 320  12 336
 154 339 222 427  15 671 618 543 269  97 448 442 199 342 107 609 268 485
  62 647 205 264 563 359 317 591 484  23 178 399 221  88 120 126 632 590
 309 387 502 303 195 358 363 394 508 565 650 101  14   8 466]

In [ ]:
titanic['Embarked']=le.fit_transform(titanic['Embarked'])
print(titanic['Embarked'].unique())

[2 0 1]

In [ ]:
ip=titanic[[	'Name',	'Sex',	'Age',	'SibSp',	'Parch',	'Ticket',	'Fare',	'Cabin']]
op=titanic['Survived']

In [ ]:
print(ip.shape)
print(op.shape)
print(titanic.shape)

(891, 9)
(891,)
(891, 12)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(ip,op,test_size=0.4)
print(x_test,'\t',y_test,end=' ')

     Name  Sex   Age  SibSp  Parch  Ticket     Fare  Cabin
322   762    0  30.0      0      0     124  12.3500     15
68     25    0  17.0      4      2     248   7.9250     15
818   371    1  43.0      0      0     543   6.4500     15
810    10    1  26.0      0      0     339   7.8875     15
608   458    0  22.0      1      2     634  41.5792     15
..    ...  ...   ...    ...    ...     ...      ...    ...
94    184    1  59.0      0      0     428   7.2500     15
264   356    0     S      0      0     478   7.7500     15
294   541    1  24.0      0      0     374   7.8958     15
41    827    0  27.0      1      0      53  21.0000     15
206    51    1  32.0      1      0     247  15.8500     15

[357 rows x 8 columns] 	 322    1
68     1
818    0
810    0
608    1
      ..
94     0
264    0
294    0
41     0
206    0
Name: Survived, Length: 357, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

ValueError: could not convert string to float: 'S'

In [ ]:
print(x_train.dtypes)
print(x_test.dtypes)
non_numeric_cols = x_train.select_dtypes(include=["object"]).columns
print(non_numeric_cols)

Name        int64
Sex         int64
Age        object
SibSp       int64
Parch       int64
Ticket      int64
Fare      float64
Cabin       int64
dtype: object
Name        int64
Sex         int64
Age        object
SibSp       int64
Parch       int64
Ticket      int64
Fare      float64
Cabin       int64
dtype: object
Index(['Age'], dtype='object')

In [ ]:
non_numeric_cols = x_train.select_dtypes(include=["object"]).columns
print(non_numeric_cols)

Index(['Age'], dtype='object')

In [ ]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

ValueError: could not convert string to float: 'S'